version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: spotify_random
    restart: always
    environment:
      POSTGRES_DB: spotify-random
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secretPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
